config/routes.rb
Rails.application.routes.draw do
  resources :photos do
    collection do
      match 'search' => 'photos#search', via: [:get, :post], as: :search
    end
  end

  root 'home#index'

  resources :home
  resources :tags
  resources :locations
  resources :profile

end

app/models/photo.rb
class Photo < ActiveRecord::Base
  serialize :exif, JSON
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @q = Photo.ransack(params[:q])
    @photos = @q.result.page params[:page]
  end

end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController

  def index
    @q = Photo.ransack(params[:q])
    @photos = @q.result
  end

end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_photo, only: [:show, :edit, :update, :destroy]

  # GET /photos
  # GET /photos.json
  def index
    @photos = Photo.page params[:page]
  end

  # GET /photos/1
  # GET /photos/1.json
  def show
  end

  # GET /photos/new
  def new
    @photo = Photo.new
  end

  # GET /photos/1/edit
  def edit
  end

  # POST /photos
  # POST /photos.json
  def create
    @photo = Photo.new(photo_params)

    respond_to do |format|
      if @photo.save
        format.html { redirect_to @photo, notice: 'Photo was successfully created.' }
        format.json { render :show, status: :created, location: @photo }
      else
        format.html { render :new }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /photos/1
  # PATCH/PUT /photos/1.json
  def update
    respond_to do |format|
      if @photo.update(photo_params)
        format.html { redirect_to @photo, notice: 'Photo was successfully updated.' }
        format.json { render :show, status: :ok, location: @photo }
      else
        format.html { render :edit }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1
  # DELETE /photos/1.json
  def destroy
    @photo.destroy
    respond_to do |format|
      format.html { redirect_to photos_url, notice: 'Photo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def search
    @q = Photo.ransack(params[:q])
    # @photos = @q.result.near([31.2, 121.5], 20, units: :km).page params[:page]
    @photos = @q.result.page params[:page]
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_photo
      @photo = Photo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def photo_params
      params.require(:photo).permit!
      # params.require(:photo).permit(:url, :location, :tag, :exif, :name,
      #                               :longitude, :latitude, :taken_at, :author,
      #                               :author_url)
    end
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController

  def index
  end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  def index
    @q = Photo.ransack(params[:q])
    @photos = @q.result
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/home/index.html.erb
<div class="content">
  <div class="pics" style='margin: 0 50px'>
    <% @photos.each do |photo| %>
    <div class="photo" style="display: inline-block; margin: 20px;">
      <%= link_to( image_tag(photo.url), photo_path(photo)) %>
      <div class="info">
        <%= image_tag("收藏1.png", width: 16) %>
        <%= photo.name[0..5] %>
        <div class="pull-right">
          <%= image_tag("地理.png", width: 13) %>
          <%= photo.longitude.to_s[0..5] %>
        </div>

      </div>
    </div>
    <% end %>
    </div>
  </div>
</div>
</div>

<div class="footer">
  <ul class="nav nav-tabs" id="myTab" role="tablist">
    <li class="active">
      <a href="home"> <%=image_tag("home_icon.png", height: 33)%></a>
    </li>
    <li>
      <a href="locations"> <%=image_tag("地理.png", height: 33)%></a>
    </li>
    <li>
      <a href="tags"> <%=image_tag("标签icon.png", height: 33)%></a>
    </li>
    <li>
      <a href="profile"> <%=image_tag("自己icon.png", height: 33)%></a>
    </li>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Qnp</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>

    <%= yield %>

  </body>

</html>

app/views/locations/index.html.erb
<div class="content">
  <div class="search">
    <div class="col-lg-5">
      <div class="input-group">
        <%= search_form_for @q, url: home_index_path do |f| %>
        <%= f.search_field :location_cont, class: 'form-control' %>

        <%= f.submit class:'btn btn-default' %>
        <% end %>
      </div><!-- /input-group -->
    </div>
  </div>

  <div class="locations">
    <div class="section">
      <div class="section-title">
        搜索历史
      </div>
      <div class="section-list"> #开发中# </div>
    </div>

    <div class="section">
      <div class="section-title"> 热门搜索 </div>
      <div class="section-list">
        <a href="/home"> #Taiwan# </a>
      </div>
      <div class="section-list">
        <a href="/home"> #Japan# </a>
      </div>
      <div class="section-list">
        <a href="/home"> #Spain# </a>
      </div>
    </div>
  </div>
</div>

<div class="footer">
  <ul class="nav nav-tabs" id="myTab" role="tablist">
    <li class="active">
      <a href="home"> <%=image_tag("home_icon.png", height: 33)%></a>
    </li>
    <li>
      <a href="#"> <%=image_tag("地理.png", height: 33)%></a>
    </li>
    <li>
      <a href="tags"> <%=image_tag("标签icon.png", height: 33)%></a>
    </li>
    <li>
      <a href="profile"> <%=image_tag("自己icon.png", height: 33)%></a>
    </li>
  </ul>
</div>

app/views/photos/_form.html.erb
<%= form_for(@photo) do |f| %>
  <% if @photo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@photo.errors.count, "error") %> prohibited this photo from being saved:</h2>

      <ul>
      <% @photo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :tag %><br>
    <%= f.text_field :tag %>
  </div>
  <div class="field">
    <%= f.label :exif %><br>
    <%= f.text_field :exif %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br>
    <%= f.number_field :longitude %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br>
    <%= f.number_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :taken_at %><br>
    <%= f.datetime_field :taken_at %>
  </div>
  <div class="field">
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :author_url %><br>
    <%= f.url_field :author_url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/photos/edit.html.erb
<h1>Editing Photo</h1>

<%= render 'form' %>

<%= link_to 'Show', @photo %> |
<%= link_to 'Back', photos_path %>

app/views/photos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Photos</h1>

<table>
  <thead>
    <tr>
      <th>Url</th>
      <th>Location</th>
      <th>Tag</th>
      <th>Exif</th>
      <th>Name</th>
      <th>Longitude</th>
      <th>Latitude</th>
      <th>TakenAt</th>
      <th>Author</th>
      <th>AuthorUrl</th>
      <th colspan="10"></th>
    </tr>
  </thead>

  <tbody>
    <% @photos.each do |photo| %>
      <tr>
        <td><%= photo.url %></td>
        <td><%= photo.location %></td>
        <td><%= photo.tag %></td>
        <td><%= photo.exif %></td>
        <td><%= photo.name %></td>
        <td><%= photo.longitude %></td>
        <td><%= photo.latitude %></td>
        <td><%= photo.taken_at %></td>
        <td><%= photo.author %></td>
        <td><%= photo.author_url %></td>
        <td><%= link_to 'Show', photo %></td>
        <td><%= link_to 'Edit', edit_photo_path(photo) %></td>
        <td><%= link_to 'Destroy', photo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Photo', new_photo_path %>

app/views/photos/new.html.erb
<h1>New Photo</h1>

<%= render 'form' %>

<%= link_to 'Back', photos_path %>

app/views/photos/search.html.erb
<p id="notice"><%= notice %></p>

<%= search_form_for @q, url: search_photos_path do |f| %>

<%= f.label :location_cont %>
<%= f.search_field :location_cont %>

<%= f.label :tag_cont %>
<%= f.search_field :tag_cont %>

<%= f.submit %>
<% end %>

<h1>Listing Photos</h1>

<table>
  <thead>
    <tr>
      <th>Url</th>
      <th>Location</th>
      <th>Tag</th>
      <th>Exif</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @photos.each do |photo| %>
    <tr>
      <td><%= photo.url %></td>
      <td><%= photo.location %></td>
      <td><%= photo.tag %></td>
      <td><%= photo.exif %></td>
      <td><%= photo.name %></td>
      <td><%= photo.longitude %></td>
      <td><%= photo.latitude %></td>
      <td><%= photo.taken_at %></td>
      <td><%= photo.author %></td>
      <td><%= photo.author_url %></td>
      <td><%= link_to 'Show', photo %></td>
      <td><%= link_to 'Edit', edit_photo_path(photo) %></td>
      <td><%= link_to 'Destroy', photo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Photo', new_photo_path %>

app/views/photos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Url:</strong>
  <%= @photo.url %>
</p>

<p>
  <strong>Location:</strong>
  <%= @photo.location %>
</p>

<p>
  <strong>Tag:</strong>
  <%= @photo.tag %>
</p>

<p>
  <strong>Exif:</strong>
  <%= @photo.exif %>
</p>

<p>
  <strong>Name:</strong>
  <%= @photo.name %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @photo.longitude %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @photo.latitude %>
</p>

<p>
  <strong>TakenAt:</strong>
  <%= @photo.taken_at %>
</p>

<p>
  <strong>Author:</strong>
  <%= @photo.author %>
</p>

<p>
  <strong>AuthorUrl:</strong>
  <%= @photo.author_url %>
</p>

<%= link_to 'Edit', edit_photo_path(@photo) %> |
<%= link_to 'Back', photos_path %>

app/views/tags/index.html.erb
<div class="content">
  <div class="search">
    <div class="col-lg-5">
      <div class="input-group">
        <%= search_form_for @q, url: home_index_path do |f| %>
        <%= f.search_field :tag_cont, class: 'form-control' %>

        <%= f.submit class:'btn btn-default' %>
        <% end %>
      </div><!-- /input-group -->
    </div>
  </div>

  <div class="tags">
    <div class="section">
      <div class="section-title">
        搜索历史
      </div>
      <div class="section-list"> #开发中# </div>
    </div>

    <div class="section">
      <div class="section-title"> 热门搜索 </div>
      <div class="section-list">
        <a href="/home"> #夜景# </a>
      </div>
      <div class="section-list">
        <a href="/home"> #婚礼# </a>
      </div>
      <div class="section-list">
        <a href="/home"> #日出# </a>
      </div>
    </div>
  </div>
</div>

<div class="footer">
  <ul class="nav nav-tabs" id="myTab" role="tablist">
    <li class="active">
      <a href="home"> <%=image_tag("home_icon.png", height: 33)%></a>
    </li>
    <li>
      <a href="locations"> <%=image_tag("地理.png", height: 33)%></a>
    </li>
    <li>
      <a href="#"> <%=image_tag("标签icon.png", height: 33)%></a>
    </li>
    <li>
      <a href="profile"> <%=image_tag("自己icon.png", height: 33)%></a>
    </li>
  </ul>
</div>